import { GoogleGenAI, Type } from "@google/genai";
import type { FormData, ExtractedData } from '../types';

// SECURITY: The API key is retrieved securely from the environment.
// NEVER hardcode the API key directly in this file.
const apiKey = process.env.API_KEY;

if (!apiKey) {
  console.error("CRITICAL SECURITY ERROR: API_KEY is missing from environment variables.");
}

const ai = new GoogleGenAI({ apiKey: apiKey! });

const modelName = 'gemini-2.5-flash-preview-09-2025';

export const extractJobDetails = async (jobPosting: string): Promise<ExtractedData> => {
  if (!apiKey) {
    throw new Error("Security Alert: API Key is missing. Please configure your environment variables.");
  }

  const systemPrompt = "You are a data extraction expert. Your job is to parse a blob of unstructured text from a job website and return ONLY a JSON object with the following keys: contactName, contactEmail, jobTitle, jobID. If a value is not found, return null.";
  
  try {
    const response = await ai.models.generateContent({
      model: modelName,
      contents: `Extract the data from the following text: \n\n ${jobPosting}`,
      config: {
        systemInstruction: systemPrompt,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            contactName: { type: Type.STRING },
            contactEmail: { type: Type.STRING },
            jobTitle: { type: Type.STRING },
            jobID: { type: Type.STRING }
          },
        },
      },
    });

    const text = response.text;
    if (!text) {
        throw new Error("No data extracted.");
    }
    const data = JSON.parse(text);
    
    return {
        contactName: data.contactName || null,
        contactEmail: data.contactEmail || null,
        jobTitle: data.jobTitle || null,
        jobID: data.jobID || null,
    };

  } catch (error) {
    console.error("Error extracting job details:", error);
    if (error instanceof Error) {
        throw new Error(`Extraction failed: ${error.message}`);
    }
    throw new Error("An unknown error occurred during job detail extraction.");
  }
};


export const generateSmartCoverLetter = async (
  formData: Omit<FormData, 'jobPosting'>, 
  extractedData: ExtractedData, 
  jobPosting: string
): Promise<string> => {
  if (!apiKey) {
    throw new Error("Security Alert: API Key is missing.");
  }
  
  const systemPrompt = `You are a professional career coach and expert cover letter writer. Your client is an electrician from Morocco applying for jobs in Germany. Their name is ${formData.userName}. They have basic German (A1) but are fluent in English (B1+). Your task is to write a highly targeted, professional, and confident cover letter in GERMAN. You must use the provided CV text and the specific job description to highlight the user's exact skills that match the job. Address the letter to ${extractedData.contactName || 'Hiring Manager'}. The tone must be respectful, confident, and eager.`;
  
  const userPrompt = `Here is my information:
MY CV:
${formData.cv}

THEIR JOB DESCRIPTION:
${jobPosting}

JOB TITLE: ${extractedData.jobTitle || 'the advertised position'}
CONTACT PERSON: ${extractedData.contactName || 'Hiring Manager'}

Write the targeted cover letter in German.`;

  try {
    const response = await ai.models.generateContent({
      model: modelName,
      contents: userPrompt,
      config: {
        systemInstruction: systemPrompt,
      },
    });

    const text = response.text;
    if (!text) {
        throw new Error("No text was generated by the API for the cover letter.");
    }
    return text;

  } catch (error) {
    console.error("Error generating cover letter:", error);
    if (error instanceof Error) {
        throw new Error(`Generation failed: ${error.message}`);
    }
    throw new Error("An unknown error occurred during cover letter generation.");
  }
};